version: 2

models:
  - name: dim_customers
    description: "Tabela de dimensão de clientes"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_products
    description: "Tabela de dimensão de produtos"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Tabela fato de pedidos"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: fct_order_items
    description: "Tabela fato de itens de pedidos"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id